spring:
  config:
    import: optional:file:./.env[.properties]

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

loadtest:
  security:
    allowed-hosts: ${LOADTEST_ALLOWED_HOSTS}
    allowed-ports: ${LOADTEST_ALLOWED_PORTS:80,443}